// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRcu_2uhL1T-o2cON1koYC1BP2WLEM5YQ',
    appId: '1:411711991157:ios:915c9bcd20729da628373c',
    messagingSenderId: '411711991157',
    projectId: 'cash-bae5d',
    storageBucket: 'cash-bae5d.firebasestorage.app',
    iosBundleId: 'com.example.app4cash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTTQ7yATGhIeCjymU1WnVtHFXDjvClZaE',
    appId: '1:411711991157:web:2ceca6f96df48f3828373c',
    messagingSenderId: '411711991157',
    projectId: 'cash-bae5d',
    authDomain: 'cash-bae5d.firebaseapp.com',
    storageBucket: 'cash-bae5d.firebasestorage.app',
    measurementId: 'G-Y3ELT6XTVP',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTTQ7yATGhIeCjymU1WnVtHFXDjvClZaE',
    appId: '1:411711991157:web:2ceca6f96df48f3828373c',
    messagingSenderId: '411711991157',
    projectId: 'cash-bae5d',
    authDomain: 'cash-bae5d.firebaseapp.com',
    storageBucket: 'cash-bae5d.firebasestorage.app',
    measurementId: 'G-Y3ELT6XTVP',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRcu_2uhL1T-o2cON1koYC1BP2WLEM5YQ',
    appId: '1:411711991157:ios:915c9bcd20729da628373c',
    messagingSenderId: '411711991157',
    projectId: 'cash-bae5d',
    storageBucket: 'cash-bae5d.firebasestorage.app',
    iosBundleId: 'com.example.app4cash',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxClLeGsFBfJrSxrtRfr5zUMcfpVk2uTM',
    appId: '1:411711991157:android:4a0ced550a347c6c28373c',
    messagingSenderId: '411711991157',
    projectId: 'cash-bae5d',
    storageBucket: 'cash-bae5d.firebasestorage.app',
  );

}